In [2]:
import numpy as np
import pandas as pd

In [3]:
customers = pd.read_csv("customers.csv")
payments = pd.read_csv("payments.csv")
subscriptions = pd.read_csv("subscriptions.csv")
support_tickets = pd.read_csv("support_tickets.csv")
monthly_usage = pd.read_csv("usage_monthly.csv")

In [8]:
customers.shape

(12000, 12)

In [9]:
customers.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'State',
       'Region', 'Signup_Date', 'Acquisition_Channel', 'Primary_Device',
       'Customer_Status', 'Churn_Date'],
      dtype='str')

In [10]:
customers.head()

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Signup_Date,Acquisition_Channel,Primary_Device,Customer_Status,Churn_Date
0,CUST00001,Customer_00001,25,Male,Surat,Gujarat,West,2025-10-16,Mobile App,Android,Active,NaN
1,CUST00002,Customer_00002,56,Male,Patna,Bihar,East,2025-06-01,Mobile App,Web,Active,NaN
2,CUST00003,Customer_00003,28,Other,Kochi,Kerala,South,2026-02-16,Retail Store,Android,Active,NaN
3,CUST00004,Customer_00004,34,Male,Coimbatore,Tamil Nadu,South,2025-09-10,Website,Web,Active,NaN
4,CUST00005,Customer_00005,22,Male,Ahmedabad,Gujarat,West,2025-12-22,Retail Store,Smart TV,Active,NaN

In [11]:
customers.tail()

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Signup_Date,Acquisition_Channel,Primary_Device,Customer_Status,Churn_Date
11995,CUST11996,Customer_11996,46,Female,Pune,Maharashtra,West,2024-09-27,Retail Store,Smart TV,Active,NaN
11996,CUST11997,Customer_11997,53,Male,Surat,Gujarat,West,2026-04-28,Retail Store,iOS,Active,NaN
11997,CUST11998,Customer_11998,43,Female,Indore,Madhya Pradesh,West,2025-05-23,Partner,Web,Active,NaN
11998,CUST11999,Customer_11999,59,Other,Surat,Gujarat,West,2024-03-20,Website,Android,Active,NaN
11999,CUST12000,Customer_12000,25,Male,Mumbai,Maharashtra,West,2026-02-10,Mobile App,iOS,Active,NaN

In [12]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          12000 non-null  str
 1   Customer_Name        12000 non-null  str
 2   Age                  12000 non-null  int64
 3   Gender               12000 non-null  str
 4   City                 12000 non-null  str
 5   State                12000 non-null  str
 6   Region               12000 non-null  str
 7   Signup_Date          12000 non-null  str
 8   Acquisition_Channel  12000 non-null  str
 9   Primary_Device       12000 non-null  str
 10  Customer_Status      12000 non-null  str
 11  Churn_Date           1606 non-null   str
dtypes: int64(1), str(11)
memory usage: 2.0 MB

In [16]:
customers["Customer_Status"].value_counts()

Customer_Status
Active     10394
Churned     1606
Name: count, dtype: int64

In [17]:
customers.groupby("Customer_Status")["Churn_Date"].count()

Customer_Status
Active        0
Churned    1606
Name: Churn_Date, dtype: int64

In [18]:
customers[
    (customers["Customer_Status"] == "Churned") &
    (customers["Churn_Date"].isna())
]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, Gender, City, State, Region, Signup_Date, Acquisition_Channel, Primary_Device, Customer_Status, Churn_Date]
Index: []

In [19]:
customers[
    (customers["Customer_Status"] == "Active") &
    (customers["Churn_Date"].isna())
]

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Signup_Date,Acquisition_Channel,Primary_Device,Customer_Status,Churn_Date
0,CUST00001,Customer_00001,25,Male,Surat,Gujarat,West,2025-10-16,Mobile App,Android,Active,NaN
1,CUST00002,Customer_00002,56,Male,Patna,Bihar,East,2025-06-01,Mobile App,Web,Active,NaN
2,CUST00003,Customer_00003,28,Other,Kochi,Kerala,South,2026-02-16,Retail Store,Android,Active,NaN
3,CUST00004,Customer_00004,34,Male,Coimbatore,Tamil Nadu,South,2025-09-10,Website,Web,Active,NaN
4,CUST00005,Customer_00005,22,Male,Ahmedabad,Gujarat,West,2025-12-22,Retail Store,Smart TV,Active,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
11995,CUST11996,Customer_11996,46,Female,Pune,Maharashtra,West,2024-09-27,Retail Store,Smart TV,Active,NaN
11996,CUST11997,Customer_11997,53,Male,Surat,Gujarat,West,2026-04-28,Retail Store,iOS,Active,NaN
11997,CUST11998,Customer_11998,43,Female,Indore,Madhya Pradesh,West,2025-05-23,Partner,Web,Active,NaN
11998,CUST11999,Customer_11999,59,Other,Surat,Gujarat,West,2024-03-20,Website,Android,Active,NaN
11999,CUST12000,Customer_12000,25,Male,Mumbai,Maharashtra,West,2026-02-10,Mobile App,iOS,Active,NaN

In [20]:
customers.dtypes

Customer_ID              str
Customer_Name            str
Age                    int64
Gender                   str
City                     str
State                    str
Region                   str
Signup_Date              str
Acquisition_Channel      str
Primary_Device           str
Customer_Status          str
Churn_Date               str
dtype: object

In [21]:
customers.describe()

                Age
count  12000.000000
mean      43.106500
std       14.668228
min       18.000000
25%       30.000000
50%       43.000000
75%       56.000000
max       68.000000

In [22]:
customers.describe(include = "all")

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Signup_Date,Acquisition_Channel,Primary_Device,Customer_Status,Churn_Date
count,12000,12000,12000.000000,12000,12000,12000,12000,12000,12000,12000,12000,1606
unique,12000,12000,NaN,3,20,16,4,851,4,4,2,121
top,CUST00001,Customer_00001,NaN,Male,Ahmedabad,Gujarat,West,2025-07-07,Website,Smart TV,Active,2026-05-27
freq,1,1,NaN,4094,637,1250,3050,26,3070,3023,10394,24
mean,NaN,NaN,43.106500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,14.668228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,43.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,56.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,68.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
customers["Customer_ID"].unique()

<ArrowStringArray>
['CUST00001', 'CUST00002', 'CUST00003', 'CUST00004', 'CUST00005', 'CUST00006',
 'CUST00007', 'CUST00008', 'CUST00009', 'CUST00010',
 ...
 'CUST11991', 'CUST11992', 'CUST11993', 'CUST11994', 'CUST11995', 'CUST11996',
 'CUST11997', 'CUST11998', 'CUST11999', 'CUST12000']
Length: 12000, dtype: str

In [25]:
customers["Customer_ID"].nunique()

12000

In [26]:
customers["Region"].value_counts()

Region
West     3050
South    3005
East     2981
North    2964
Name: count, dtype: int64

In [27]:
customers.isnull().sum()

Customer_ID                0
Customer_Name              0
Age                        0
Gender                     0
City                       0
State                      0
Region                     0
Signup_Date                0
Acquisition_Channel        0
Primary_Device             0
Customer_Status            0
Churn_Date             10394
dtype: int64

In [28]:
customers.isnull().values.any()

np.True_

In [29]:
customers.isnull().mean()*100

Customer_ID             0.000000
Customer_Name           0.000000
Age                     0.000000
Gender                  0.000000
City                    0.000000
State                   0.000000
Region                  0.000000
Signup_Date             0.000000
Acquisition_Channel     0.000000
Primary_Device          0.000000
Customer_Status         0.000000
Churn_Date             86.616667
dtype: float64

In [30]:
customers.duplicated().sum()

np.int64(0)

In [31]:
customers[customers.duplicated(keep=False)]

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, Gender, City, State, Region, Signup_Date, Acquisition_Channel, Primary_Device, Customer_Status, Churn_Date]
Index: []

In [32]:
customers["Customer_ID"].nunique() == len(customers)

True

In [34]:
customers["Age"].nunique() == len(customers)

False

In [36]:
customers["Signup_Date"].isnull().sum()

np.int64(0)

In [37]:
customers["Churn_Date"].isnull().sum()

np.int64(10394)

In [38]:
customers["Customer_Status"].isnull().sum()

np.int64(0)

In [43]:
print(customers["Signup_Date"].min())
print(customers["Signup_Date"].max())

2024-01-01
2026-04-30

In [44]:
customers["Signup_Date"] = pd.to_datetime(customers["Signup_Date"])
customers["Churn_Date"] = pd.to_datetime(customers["Churn_Date"])

In [45]:
customers.info

<bound method DataFrame.info of       Customer_ID   Customer_Name  Age  Gender        City           State  \
0       CUST00001  Customer_00001   25    Male       Surat         Gujarat
1       CUST00002  Customer_00002   56    Male       Patna           Bihar
2       CUST00003  Customer_00003   28   Other       Kochi          Kerala
3       CUST00004  Customer_00004   34    Male  Coimbatore      Tamil Nadu
4       CUST00005  Customer_00005   22    Male   Ahmedabad         Gujarat
...           ...             ...  ...     ...         ...             ...
11995   CUST11996  Customer_11996   46  Female        Pune     Maharashtra
11996   CUST11997  Customer_11997   53    Male       Surat         Gujarat
11997   CUST11998  Customer_11998   43  Female      Indore  Madhya Pradesh
11998   CUST11999  Customer_11999   59   Other       Surat         Gujarat
11999   CUST12000  Customer_12000   25    Male      Mumbai     Maharashtra

      Region Signup_Date Acquisition_Channel Primary_Device Customer_Status  \
0       West  2025-10-16          Mobile App        Android          Active
1       East  2025-06-01          Mobile App            Web          Active
2      South  2026-02-16        Retail Store        Android          Active
3      South  2025-09-10             Website            Web          Active
4       West  2025-12-22        Retail Store       Smart TV          Active
...      ...         ...                 ...            ...             ...
11995   West  2024-09-27        Retail Store       Smart TV          Active
11996   West  2026-04-28        Retail Store            iOS          Active
11997   West  2025-05-23             Partner            Web          Active
11998   West  2024-03-20             Website        Android          Active
11999   West  2026-02-10          Mobile App            iOS          Active

      Churn_Date
0            NaT
1            NaT
2            NaT
3            NaT
4            NaT
...          ...
11995        NaT
11996        NaT
11997        NaT
11998        NaT
11999        NaT

[12000 rows x 12 columns]>

In [46]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          12000 non-null  str
 1   Customer_Name        12000 non-null  str
 2   Age                  12000 non-null  int64
 3   Gender               12000 non-null  str
 4   City                 12000 non-null  str
 5   State                12000 non-null  str
 6   Region               12000 non-null  str
 7   Signup_Date          12000 non-null  datetime64[us]
 8   Acquisition_Channel  12000 non-null  str
 9   Primary_Device       12000 non-null  str
 10  Customer_Status      12000 non-null  str
 11  Churn_Date           1606 non-null   datetime64[us]
dtypes: datetime64[us](2), int64(1), str(9)
memory usage: 1.9 MB

In [47]:
customers.dtypes

Customer_ID                       str
Customer_Name                     str
Age                             int64
Gender                            str
City                              str
State                             str
Region                            str
Signup_Date            datetime64[us]
Acquisition_Channel               str
Primary_Device                    str
Customer_Status                   str
Churn_Date             datetime64[us]
dtype: object

In [48]:
payments.shape

(117521, 6)

In [49]:
payments.columns

Index(['Payment_ID', 'Customer_ID', 'Payment_Date', 'Amount', 'Payment_Method',
       'Payment_Status'],
      dtype='str')

In [50]:
payments.head()

   Payment_ID Customer_ID Payment_Date  Amount Payment_Method Payment_Status
0  PAY0000001   CUST00001   2025-10-16     799            UPI         Failed
1  PAY0000002   CUST00001   2025-11-16     799            UPI        Success
2  PAY0000003   CUST00001   2025-12-16     799            UPI        Success
3  PAY0000004   CUST00001   2026-01-16     799            UPI        Success
4  PAY0000005   CUST00001   2026-02-16     799            UPI        Success

In [51]:
payments.tail()

,Payment_ID,Customer_ID,Payment_Date,Amount,Payment_Method,Payment_Status
117516,PAY0016101,CUST01635,2024-07-18,499,Credit Card,Failed
117517,PAY0079107,CUST08072,2024-11-24,1499,Net Banking,Success
117518,PAY0006185,CUST00629,2026-03-16,2998,UPI,Success
117519,PAY0114522,CUST11697,2025-04-18,14388,UPI,Success
117520,PAY0112755,CUST11511,2025-04-17,499,AutoPay,Success

In [52]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 117521 entries, 0 to 117520
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Payment_ID      117521 non-null  str
 1   Customer_ID     117521 non-null  str
 2   Payment_Date    117521 non-null  str
 3   Amount          117521 non-null  int64
 4   Payment_Method  117521 non-null  str
 5   Payment_Status  117521 non-null  str
dtypes: int64(1), str(5)
memory usage: 10.3 MB

In [53]:
payments.dtypes

Payment_ID          str
Customer_ID         str
Payment_Date        str
Amount            int64
Payment_Method      str
Payment_Status      str
dtype: object

In [54]:
payments.describe()

              Amount
count  117521.000000
mean     2043.614903
std      3160.825108
min       499.000000
25%       799.000000
50%      1199.000000
75%      1499.000000
max     17988.000000

In [55]:
payments.describe(include="all")

,Payment_ID,Customer_ID,Payment_Date,Amount,Payment_Method,Payment_Status
count,117521,117521,117521,117521.000000,117521,117521
unique,117501,12000,812,NaN,5,2
top,PAY0006185,CUST01635,2025-01-28,NaN,Net Banking,Success
freq,2,13,586,NaN,24200,108419
mean,NaN,NaN,NaN,2043.614903,NaN,NaN
std,NaN,NaN,NaN,3160.825108,NaN,NaN
min,NaN,NaN,NaN,499.000000,NaN,NaN
25%,NaN,NaN,NaN,799.000000,NaN,NaN
50%,NaN,NaN,NaN,1199.000000,NaN,NaN
75%,NaN,NaN,NaN,1499.000000,NaN,NaN
max,NaN,NaN,NaN,17988.000000,NaN,NaN

In [58]:
payments["Payment_ID"].unique()

<ArrowStringArray>
['PAY0000001', 'PAY0000002', 'PAY0000003', 'PAY0000004', 'PAY0000005',
 'PAY0000006', 'PAY0000007', 'PAY0000008', 'PAY0000009', 'PAY0000010',
 ...
 'PAY0117492', 'PAY0117493', 'PAY0117494', 'PAY0117495', 'PAY0117496',
 'PAY0117497', 'PAY0117498', 'PAY0117499', 'PAY0117500', 'PAY0117501']
Length: 117501, dtype: str

In [57]:
payments["Customer_ID"].unique()

<ArrowStringArray>
['CUST00001', 'CUST00002', 'CUST00003', 'CUST00004', 'CUST00005', 'CUST00006',
 'CUST00007', 'CUST00008', 'CUST00009', 'CUST00010',
 ...
 'CUST11991', 'CUST11992', 'CUST11993', 'CUST11994', 'CUST11995', 'CUST11996',
 'CUST11997', 'CUST11998', 'CUST11999', 'CUST12000']
Length: 12000, dtype: str

In [60]:
payments["Payment_ID"].value_counts()

Payment_ID
PAY0006185    2
PAY0006419    2
PAY0008853    2
PAY0016101    2
PAY0030622    2
             ..
PAY0117497    1
PAY0117498    1
PAY0117499    1
PAY0117500    1
PAY0117501    1
Name: count, Length: 117501, dtype: int64

In [61]:
payments.isnull().sum()

Payment_ID        0
Customer_ID       0
Payment_Date      0
Amount            0
Payment_Method    0
Payment_Status    0
dtype: int64

In [62]:
payments.isnull().values.any()

np.False_

In [64]:
payments.isnull().mean()*100

Payment_ID        0.0
Customer_ID       0.0
Payment_Date      0.0
Amount            0.0
Payment_Method    0.0
Payment_Status    0.0
dtype: float64

In [65]:
payments.duplicated().sum()

np.int64(20)

In [66]:
payments[payments.duplicated(keep=False)]

,Payment_ID,Customer_ID,Payment_Date,Amount,Payment_Method,Payment_Status
6184,PAY0006185,CUST00629,2026-03-16,2998,UPI,Success
6418,PAY0006419,CUST00653,2026-02-20,499,UPI,Success
8852,PAY0008853,CUST00891,2026-01-26,1497,UPI,Success
16100,PAY0016101,CUST01635,2024-07-18,499,Credit Card,Failed
30621,PAY0030622,CUST03121,2025-03-25,4497,Net Banking,Success
38524,PAY0038525,CUST03924,2026-02-14,499,Credit Card,Success
47086,PAY0047087,CUST04793,2026-03-28,1499,Debit Card,Success
53224,PAY0053225,CUST05427,2025-04-23,799,UPI,Failed
65069,PAY0065070,CUST06643,2024-10-27,1199,Net Banking,Failed
65810,PAY0065811,CUST06726,2024-06-10,1199,AutoPay,Success
79106,PAY0079107,CUST08072,2024-11-24,1499,Net Banking,Success
81950,PAY0081951,CUST08357,2024-10-03,1499,AutoPay,Success
95423,PAY0095424,CUST09740,2024-05-06,4497,Net Banking,Success
96834,PAY0096835,CUST09879,2025-04-02,499,UPI,Success
97877,PAY0097878,CUST09987,2024-11-28,1199,UPI,Success
98937,PAY0098938,CUST10093,2024-08-24,499,Credit Card,Success
105886,PAY0105887,CUST10811,2026-02-21,1499,Net Banking,Success
112754,PAY0112755,CUST11511,2025-04-17,499,AutoPay,Success
114521,PAY0114522,CUST11697,2025-04-18,14388,UPI,Success
117314,PAY0117315,CUST11982,2024-02-04,1199,Debit Card,Success
117501,PAY0065070,CUST06643,2024-10-27,1199,Net Banking,Failed
117502,PAY0030622,CUST03121,2025-03-25,4497,Net Banking,Success
117503,PAY0065811,CUST06726,2024-06-10,1199,AutoPay,Success
117504,PAY0098938,CUST10093,2024-08-24,499,Credit Card,Success
117505,PAY0095424,CUST09740,2024-05-06,4497,Net Banking,Success
117506,PAY0105887,CUST10811,2026-02-21,1499,Net Banking,Success
117507,PAY0096835,CUST09879,2025-04-02,499,UPI,Success
117508,PAY0008853,CUST00891,2026-01-26,1497,UPI,Success
117509,PAY0047087,CUST04793,2026-03-28,1499,Debit Card,Success
117510,PAY0006419,CUST00653,2026-02-20,499,UPI,Success
117511,PAY0081951,CUST08357,2024-10-03,1499,AutoPay,Success
117512,PAY0097878,CUST09987,2024-11-28,1199,UPI,Success
117513,PAY0053225,CUST05427,2025-04-23,799,UPI,Failed
117514,PAY0117315,CUST11982,2024-02-04,1199,Debit Card,Success
117515,PAY0038525,CUST03924,2026-02-14,499,Credit Card,Success
117516,PAY0016101,CUST01635,2024-07-18,499,Credit Card,Failed
117517,PAY0079107,CUST08072,2024-11-24,1499,Net Banking,Success
117518,PAY0006185,CUST00629,2026-03-16,2998,UPI,Success
117519,PAY0114522,CUST11697,2025-04-18,14388,UPI,Success
117520,PAY0112755,CUST11511,2025-04-17,499,AutoPay,Success

In [67]:
payments[payments["Payment_ID"].duplicated(keep=False)].sort_values("Payment_ID")

,Payment_ID,Customer_ID,Payment_Date,Amount,Payment_Method,Payment_Status
6184,PAY0006185,CUST00629,2026-03-16,2998,UPI,Success
117518,PAY0006185,CUST00629,2026-03-16,2998,UPI,Success
6418,PAY0006419,CUST00653,2026-02-20,499,UPI,Success
117510,PAY0006419,CUST00653,2026-02-20,499,UPI,Success
8852,PAY0008853,CUST00891,2026-01-26,1497,UPI,Success
117508,PAY0008853,CUST00891,2026-01-26,1497,UPI,Success
16100,PAY0016101,CUST01635,2024-07-18,499,Credit Card,Failed
117516,PAY0016101,CUST01635,2024-07-18,499,Credit Card,Failed
30621,PAY0030622,CUST03121,2025-03-25,4497,Net Banking,Success
117502,PAY0030622,CUST03121,2025-03-25,4497,Net Banking,Success
38524,PAY0038525,CUST03924,2026-02-14,499,Credit Card,Success
117515,PAY0038525,CUST03924,2026-02-14,499,Credit Card,Success
47086,PAY0047087,CUST04793,2026-03-28,1499,Debit Card,Success
117509,PAY0047087,CUST04793,2026-03-28,1499,Debit Card,Success
53224,PAY0053225,CUST05427,2025-04-23,799,UPI,Failed
117513,PAY0053225,CUST05427,2025-04-23,799,UPI,Failed
65069,PAY0065070,CUST06643,2024-10-27,1199,Net Banking,Failed
117501,PAY0065070,CUST06643,2024-10-27,1199,Net Banking,Failed
65810,PAY0065811,CUST06726,2024-06-10,1199,AutoPay,Success
117503,PAY0065811,CUST06726,2024-06-10,1199,AutoPay,Success
79106,PAY0079107,CUST08072,2024-11-24,1499,Net Banking,Success
117517,PAY0079107,CUST08072,2024-11-24,1499,Net Banking,Success
81950,PAY0081951,CUST08357,2024-10-03,1499,AutoPay,Success
117511,PAY0081951,CUST08357,2024-10-03,1499,AutoPay,Success
95423,PAY0095424,CUST09740,2024-05-06,4497,Net Banking,Success
117505,PAY0095424,CUST09740,2024-05-06,4497,Net Banking,Success
96834,PAY0096835,CUST09879,2025-04-02,499,UPI,Success
117507,PAY0096835,CUST09879,2025-04-02,499,UPI,Success
97877,PAY0097878,CUST09987,2024-11-28,1199,UPI,Success
117512,PAY0097878,CUST09987,2024-11-28,1199,UPI,Success
98937,PAY0098938,CUST10093,2024-08-24,499,Credit Card,Success
117504,PAY0098938,CUST10093,2024-08-24,499,Credit Card,Success
105886,PAY0105887,CUST10811,2026-02-21,1499,Net Banking,Success
117506,PAY0105887,CUST10811,2026-02-21,1499,Net Banking,Success
112754,PAY0112755,CUST11511,2025-04-17,499,AutoPay,Success
117520,PAY0112755,CUST11511,2025-04-17,499,AutoPay,Success
114521,PAY0114522,CUST11697,2025-04-18,14388,UPI,Success
117519,PAY0114522,CUST11697,2025-04-18,14388,UPI,Success
117314,PAY0117315,CUST11982,2024-02-04,1199,Debit Card,Success
117514,PAY0117315,CUST11982,2024-02-04,1199,Debit Card,Success

In [69]:
payments.duplicated().sum()

np.int64(20)

In [70]:
payments = payments.drop_duplicates()

In [71]:
print("Rows:", len(payments))
print("Unique Payment IDs:", payments["Payment_ID"].nunique())
print("Duplicate Payment IDs:", payments["Payment_ID"].duplicated().sum())

Rows: 117501
Unique Payment IDs: 117501
Duplicate Payment IDs: 0

In [72]:
payments.shape

(117501, 6)

In [73]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 117501 entries, 0 to 117500
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Payment_ID      117501 non-null  str
 1   Customer_ID     117501 non-null  str
 2   Payment_Date    117501 non-null  str
 3   Amount          117501 non-null  int64
 4   Payment_Method  117501 non-null  str
 5   Payment_Status  117501 non-null  str
dtypes: int64(1), str(5)
memory usage: 10.4 MB

In [74]:
payments.describe()

              Amount
count  117501.000000
mean     2043.601374
std      3160.844334
min       499.000000
25%       799.000000
50%      1199.000000
75%      1499.000000
max     17988.000000

In [75]:
payments["Payment_ID"].unique()

<ArrowStringArray>
['PAY0000001', 'PAY0000002', 'PAY0000003', 'PAY0000004', 'PAY0000005',
 'PAY0000006', 'PAY0000007', 'PAY0000008', 'PAY0000009', 'PAY0000010',
 ...
 'PAY0117492', 'PAY0117493', 'PAY0117494', 'PAY0117495', 'PAY0117496',
 'PAY0117497', 'PAY0117498', 'PAY0117499', 'PAY0117500', 'PAY0117501']
Length: 117501, dtype: str

In [97]:
payments["Customer_ID"].unique()

<ArrowStringArray>
['CUST00001', 'CUST00002', 'CUST00003', 'CUST00004', 'CUST00005', 'CUST00006',
 'CUST00007', 'CUST00008', 'CUST00009', 'CUST00010',
 ...
 'CUST11991', 'CUST11992', 'CUST11993', 'CUST11994', 'CUST11995', 'CUST11996',
 'CUST11997', 'CUST11998', 'CUST11999', 'CUST12000']
Length: 12000, dtype: str

In [101]:
payments["Payment_ID"].nunique() == len(payments)

True

In [99]:
payments["Customer_ID"].nunique() == len(customers)

True

In [76]:
payments.isnull().sum()

Payment_ID        0
Customer_ID       0
Payment_Date      0
Amount            0
Payment_Method    0
Payment_Status    0
dtype: int64

In [77]:
payments.duplicated().sum()

np.int64(0)

In [100]:
payments[payments.duplicated(keep=False)]

Empty DataFrame
Columns: [Payment_ID, Customer_ID, Payment_Date, Amount, Payment_Method, Payment_Status]
Index: []

In [78]:
 payments.isna().sum()

Payment_ID        0
Customer_ID       0
Payment_Date      0
Amount            0
Payment_Method    0
Payment_Status    0
dtype: int64

In [79]:
print(payments["Payment_Date"].min())

2024-01-01

In [80]:
print(payments["Payment_Date"].max())

2026-05-28

In [81]:
subscriptions.shape

(12000, 7)

In [82]:
subscriptions.columns

Index(['Subscription_ID', 'Customer_ID', 'Plan', 'Monthly_Fee',
       'Contract_Type', 'Support_Tier', 'Start_Date'],
      dtype='str')

In [83]:
subscriptions.head()

,Subscription_ID,Customer_ID,Plan,Monthly_Fee,Contract_Type,Support_Tier,Start_Date
0,SUB00001,CUST00001,Standard,799,Monthly,5,2025-10-16
1,SUB00002,CUST00002,Family,1499,Monthly,15,2025-06-01
2,SUB00003,CUST00003,Premium,1199,Monthly,10,2026-02-16
3,SUB00004,CUST00004,Family,1499,Monthly,15,2025-09-10
4,SUB00005,CUST00005,Basic,499,Annual,2,2025-12-22

In [84]:
subscriptions.tail()

,Subscription_ID,Customer_ID,Plan,Monthly_Fee,Contract_Type,Support_Tier,Start_Date
11995,SUB11996,CUST11996,Standard,799,Monthly,5,2024-09-27
11996,SUB11997,CUST11997,Basic,499,Monthly,2,2026-04-28
11997,SUB11998,CUST11998,Family,1499,Monthly,15,2025-05-23
11998,SUB11999,CUST11999,Premium,1199,Annual,10,2024-03-20
11999,SUB12000,CUST12000,Basic,499,Monthly,2,2026-02-10

In [85]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Subscription_ID  12000 non-null  str
 1   Customer_ID      12000 non-null  str
 2   Plan             12000 non-null  str
 3   Monthly_Fee      12000 non-null  int64
 4   Contract_Type    12000 non-null  str
 5   Support_Tier     12000 non-null  int64
 6   Start_Date       12000 non-null  str
dtypes: int64(2), str(5)
memory usage: 1.1 MB

In [86]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 117501 entries, 0 to 117500
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Payment_ID      117501 non-null  str
 1   Customer_ID     117501 non-null  str
 2   Payment_Date    117501 non-null  str
 3   Amount          117501 non-null  int64
 4   Payment_Method  117501 non-null  str
 5   Payment_Status  117501 non-null  str
dtypes: int64(1), str(5)
memory usage: 10.4 MB

In [87]:
payments["Payment_Date"]= pd.to_datetime(payments["Payment_Date"])

In [89]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 117501 entries, 0 to 117500
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Payment_ID      117501 non-null  str
 1   Customer_ID     117501 non-null  str
 2   Payment_Date    117501 non-null  datetime64[us]
 3   Amount          117501 non-null  int64
 4   Payment_Method  117501 non-null  str
 5   Payment_Status  117501 non-null  str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 9.3 MB

In [90]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Subscription_ID  12000 non-null  str
 1   Customer_ID      12000 non-null  str
 2   Plan             12000 non-null  str
 3   Monthly_Fee      12000 non-null  int64
 4   Contract_Type    12000 non-null  str
 5   Support_Tier     12000 non-null  int64
 6   Start_Date       12000 non-null  str
dtypes: int64(2), str(5)
memory usage: 1.1 MB

In [91]:
subscriptions.dtypes

Subscription_ID      str
Customer_ID          str
Plan                 str
Monthly_Fee        int64
Contract_Type        str
Support_Tier       int64
Start_Date           str
dtype: object

In [92]:
subscriptions.describe()

        Monthly_Fee  Support_Tier
count  12000.000000  12000.000000
mean     994.000000      7.940083
std      382.193894      4.961372
min      499.000000      2.000000
25%      499.000000      2.000000
50%      799.000000      5.000000
75%     1199.000000     10.000000
max     1499.000000     15.000000

In [93]:
subscriptions.describe(include="all")

,Subscription_ID,Customer_ID,Plan,Monthly_Fee,Contract_Type,Support_Tier,Start_Date
count,12000,12000,12000,12000.000000,12000,12000.000000,12000
unique,12000,12000,4,NaN,3,NaN,851
top,SUB00001,CUST00001,Basic,NaN,Monthly,NaN,2025-07-07
freq,1,1,3093,NaN,6504,NaN,26
mean,NaN,NaN,NaN,994.000000,NaN,7.940083,NaN
std,NaN,NaN,NaN,382.193894,NaN,4.961372,NaN
min,NaN,NaN,NaN,499.000000,NaN,2.000000,NaN
25%,NaN,NaN,NaN,499.000000,NaN,2.000000,NaN
50%,NaN,NaN,NaN,799.000000,NaN,5.000000,NaN
75%,NaN,NaN,NaN,1199.000000,NaN,10.000000,NaN
max,NaN,NaN,NaN,1499.000000,NaN,15.000000,NaN

In [94]:
subscriptions["Subscription_ID"].unique()

<ArrowStringArray>
['SUB00001', 'SUB00002', 'SUB00003', 'SUB00004', 'SUB00005', 'SUB00006',
 'SUB00007', 'SUB00008', 'SUB00009', 'SUB00010',
 ...
 'SUB11991', 'SUB11992', 'SUB11993', 'SUB11994', 'SUB11995', 'SUB11996',
 'SUB11997', 'SUB11998', 'SUB11999', 'SUB12000']
Length: 12000, dtype: str

In [95]:
subscriptions["Subscription_ID"].nunique()

12000

In [96]:
subscriptions["Customer_ID"].unique()

<ArrowStringArray>
['CUST00001', 'CUST00002', 'CUST00003', 'CUST00004', 'CUST00005', 'CUST00006',
 'CUST00007', 'CUST00008', 'CUST00009', 'CUST00010',
 ...
 'CUST11991', 'CUST11992', 'CUST11993', 'CUST11994', 'CUST11995', 'CUST11996',
 'CUST11997', 'CUST11998', 'CUST11999', 'CUST12000']
Length: 12000, dtype: str

In [103]:
subscriptions["Subscription_ID"].value_counts()

Subscription_ID
SUB00001    1
SUB00002    1
SUB00003    1
SUB00004    1
SUB00005    1
           ..
SUB11996    1
SUB11997    1
SUB11998    1
SUB11999    1
SUB12000    1
Name: count, Length: 12000, dtype: int64

In [104]:
subscriptions["Customer_ID"].value_counts()

Customer_ID
CUST00001    1
CUST00002    1
CUST00003    1
CUST00004    1
CUST00005    1
            ..
CUST11996    1
CUST11997    1
CUST11998    1
CUST11999    1
CUST12000    1
Name: count, Length: 12000, dtype: int64

In [105]:
subscriptions.isnull().sum()

Subscription_ID    0
Customer_ID        0
Plan               0
Monthly_Fee        0
Contract_Type      0
Support_Tier       0
Start_Date         0
dtype: int64

In [106]:
subscriptions.isnull().values.any()

np.False_

In [108]:
subscriptions.duplicated().sum()

np.int64(0)

In [110]:
subscriptions[subscriptions.duplicated(keep=False)]

Empty DataFrame
Columns: [Subscription_ID, Customer_ID, Plan, Monthly_Fee, Contract_Type, Support_Tier, Start_Date]
Index: []

In [111]:
subscriptions.isna().sum()

Subscription_ID    0
Customer_ID        0
Plan               0
Monthly_Fee        0
Contract_Type      0
Support_Tier       0
Start_Date         0
dtype: int64

In [112]:
print(subscriptions["Start_Date"].min())

2024-01-01

In [113]:
print(subscriptions["Start_Date"].max())

2026-04-30

In [116]:
subscriptions["Start_Date"] = pd.to_datetime(subscriptions["Start_Date"])

In [117]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Subscription_ID  12000 non-null  str
 1   Customer_ID      12000 non-null  str
 2   Plan             12000 non-null  str
 3   Monthly_Fee      12000 non-null  int64
 4   Contract_Type    12000 non-null  str
 5   Support_Tier     12000 non-null  int64
 6   Start_Date       12000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 1015.3 KB

In [118]:
support_tickets.shape

(9365, 8)

In [119]:
support_tickets.columns

Index(['Ticket_ID', 'Customer_ID', 'Ticket_Date', 'Issue_Type', 'Priority',
       'Resolution_Days', 'Satisfaction_Score', 'Contact_Channel'],
      dtype='str')

In [123]:
support_tickets.head()

,Ticket_ID,Customer_ID,Ticket_Date,Issue_Type,Priority,Resolution_Days,Satisfaction_Score,Contact_Channel
0,TKT000001,CUST00001,2025-11-03,Billing,Low,4,4.0,Chat
1,TKT000002,CUST00003,2026-04-15,Billing,Low,4,4.0,Phone
2,TKT000003,CUST00005,2026-04-27,Other,Medium,2,4.0,Chat
3,TKT000004,CUST00006,2026-03-22,Billing,Low,3,4.0,Email
4,TKT000005,CUST00007,2026-05-15,Plan Change,Medium,4,3.0,App

In [124]:
support_tickets.tail()

,Ticket_ID,Customer_ID,Ticket_Date,Issue_Type,Priority,Resolution_Days,Satisfaction_Score,Contact_Channel
9360,TKT009361,CUST11997,2026-06-23,Plan Change,Low,3,5.0,Phone
9361,TKT009362,CUST11998,2026-01-05,Technical,Medium,2,3.0,Chat
9362,TKT009363,CUST12000,2026-05-02,Billing,Low,1,4.0,Email
9363,TKT009364,CUST12000,2026-05-24,Technical,Low,4,3.0,Chat
9364,TKT009365,CUST12000,2026-06-01,Connectivity,Low,4,4.0,Email

In [125]:
support_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 9365 entries, 0 to 9364
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticket_ID           9365 non-null   str
 1   Customer_ID         9365 non-null   str
 2   Ticket_Date         9365 non-null   str
 3   Issue_Type          9365 non-null   str
 4   Priority            9365 non-null   str
 5   Resolution_Days     9365 non-null   int64
 6   Satisfaction_Score  9330 non-null   float64
 7   Contact_Channel     9365 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 1004.0 KB

In [127]:
support_tickets.dtypes

Ticket_ID                 str
Customer_ID               str
Ticket_Date               str
Issue_Type                str
Priority                  str
Resolution_Days         int64
Satisfaction_Score    float64
Contact_Channel           str
dtype: object

In [128]:
support_tickets.describe()

       Resolution_Days  Satisfaction_Score
count      9365.000000         9330.000000
mean          3.743727            3.654019
std           2.526133            0.859716
min           1.000000            1.000000
25%           2.000000            3.000000
50%           3.000000            4.000000
75%           5.000000            4.000000
max          28.000000            5.000000

In [129]:
support_tickets.describe(include="all")

,Ticket_ID,Customer_ID,Ticket_Date,Issue_Type,Priority,Resolution_Days,Satisfaction_Score,Contact_Channel
count,9365,9365,9365,9365,9365,9365.000000,9330.000000,9365
unique,9365,6414,814,6,3,NaN,NaN,4
top,TKT000001,CUST03959,2026-05-24,Connectivity,Low,NaN,NaN,Phone
freq,1,6,47,1586,5081,NaN,NaN,2391
mean,NaN,NaN,NaN,NaN,NaN,3.743727,3.654019,NaN
std,NaN,NaN,NaN,NaN,NaN,2.526133,0.859716,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,2.000000,3.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,3.000000,4.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,5.000000,4.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,28.000000,5.000000,NaN

In [134]:
support_tickets["Ticket_ID"].is_unique

True

In [135]:
support_tickets["Customer_ID"].is_unique

False

In [136]:
support_tickets["Ticket_ID"].unique()

<ArrowStringArray>
['TKT000001', 'TKT000002', 'TKT000003', 'TKT000004', 'TKT000005', 'TKT000006',
 'TKT000007', 'TKT000008', 'TKT000009', 'TKT000010',
 ...
 'TKT009356', 'TKT009357', 'TKT009358', 'TKT009359', 'TKT009360', 'TKT009361',
 'TKT009362', 'TKT009363', 'TKT009364', 'TKT009365']
Length: 9365, dtype: str

In [139]:
support_tickets["Ticket_ID"].nunique()

9365

In [141]:
support_tickets["Ticket_ID"].nunique()==len(support_tickets)

True

In [140]:
support_tickets["Ticket_ID"].value_counts()

Ticket_ID
TKT000001    1
TKT000002    1
TKT000003    1
TKT000004    1
TKT000005    1
            ..
TKT009361    1
TKT009362    1
TKT009363    1
TKT009364    1
TKT009365    1
Name: count, Length: 9365, dtype: int64

In [142]:
support_tickets["Ticket_ID"].value_counts(normalize=True)*100

Ticket_ID
TKT000001    0.010678
TKT000002    0.010678
TKT000003    0.010678
TKT000004    0.010678
TKT000005    0.010678
               ...
TKT009361    0.010678
TKT009362    0.010678
TKT009363    0.010678
TKT009364    0.010678
TKT009365    0.010678
Name: proportion, Length: 9365, dtype: float64

In [143]:
support_tickets["Ticket_ID"].value_counts(dropna=False)

Ticket_ID
TKT000001    1
TKT000002    1
TKT000003    1
TKT000004    1
TKT000005    1
            ..
TKT009361    1
TKT009362    1
TKT009363    1
TKT009364    1
TKT009365    1
Name: count, Length: 9365, dtype: int64

In [144]:
support_tickets.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9360    False
9361    False
9362    False
9363    False
9364    False
Length: 9365, dtype: bool

In [145]:
support_tickets.duplicated().sum()

np.int64(0)

In [162]:
support_tickets["Ticket_ID"].nunique()==len(support_tickets)

True

In [163]:
support_tickets[support_tickets["Ticket_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Ticket_Date, Issue_Type, Priority, Resolution_Days, Satisfaction_Score, Contact_Channel]
Index: []

In [164]:
support_tickets.drop_duplicates(keep=False)

,Ticket_ID,Customer_ID,Ticket_Date,Issue_Type,Priority,Resolution_Days,Satisfaction_Score,Contact_Channel
0,TKT000001,CUST00001,2025-11-03,Billing,Low,4,4.0,Chat
1,TKT000002,CUST00003,2026-04-15,Billing,Low,4,4.0,Phone
2,TKT000003,CUST00005,2026-04-27,Other,Medium,2,4.0,Chat
3,TKT000004,CUST00006,2026-03-22,Billing,Low,3,4.0,Email
4,TKT000005,CUST00007,2026-05-15,Plan Change,Medium,4,3.0,App
...,...,...,...,...,...,...,...,...
9360,TKT009361,CUST11997,2026-06-23,Plan Change,Low,3,5.0,Phone
9361,TKT009362,CUST11998,2026-01-05,Technical,Medium,2,3.0,Chat
9362,TKT009363,CUST12000,2026-05-02,Billing,Low,1,4.0,Email
9363,TKT009364,CUST12000,2026-05-24,Technical,Low,4,3.0,Chat
9364,TKT009365,CUST12000,2026-06-01,Connectivity,Low,4,4.0,Email

In [165]:
support_tickets.isnull().sum()

Ticket_ID              0
Customer_ID            0
Ticket_Date            0
Issue_Type             0
Priority               0
Resolution_Days        0
Satisfaction_Score    35
Contact_Channel        0
dtype: int64

In [168]:
support_tickets.isnull().values.any()

np.True_

In [169]:
support_tickets.isnull().mean()*100

Ticket_ID             0.000000
Customer_ID           0.000000
Ticket_Date           0.000000
Issue_Type            0.000000
Priority              0.000000
Resolution_Days       0.000000
Satisfaction_Score    0.373732
Contact_Channel       0.000000
dtype: float64

In [170]:
support_tickets.isna().sum()

Ticket_ID              0
Customer_ID            0
Ticket_Date            0
Issue_Type             0
Priority               0
Resolution_Days        0
Satisfaction_Score    35
Contact_Channel        0
dtype: int64

In [171]:
support_tickets["Ticket_ID"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
9360    False
9361    False
9362    False
9363    False
9364    False
Name: Ticket_ID, Length: 9365, dtype: bool

In [173]:
support_tickets["Satisfaction_Score"].isnull().sum()

np.int64(35)

In [174]:
support_tickets[support_tickets["Satisfaction_Score"].isna()]

,Ticket_ID,Customer_ID,Ticket_Date,Issue_Type,Priority,Resolution_Days,Satisfaction_Score,Contact_Channel
321,TKT000322,CUST00417,2025-02-21,Cancellation,Medium,4,NaN,Email
592,TKT000593,CUST00752,2026-04-27,Cancellation,Low,2,NaN,Phone
908,TKT000909,CUST01157,2025-08-20,Connectivity,Low,11,NaN,Email
971,TKT000972,CUST01245,2025-07-07,Plan Change,Medium,3,NaN,Phone
1002,TKT001003,CUST01285,2025-12-03,Cancellation,Medium,6,NaN,App
1606,TKT001607,CUST02039,2026-03-07,Billing,Low,3,NaN,Phone
1791,TKT001792,CUST02293,2025-11-26,Technical,Medium,2,NaN,App
1880,TKT001881,CUST02398,2025-09-10,Technical,High,3,NaN,Email
2094,TKT002095,CUST02691,2026-04-25,Billing,Medium,12,NaN,App
2115,TKT002116,CUST02715,2026-05-17,Plan Change,Low,6,NaN,App
2133,TKT002134,CUST02731,2025-04-25,Billing,Medium,3,NaN,App
2233,TKT002234,CUST02858,2024-08-25,Other,Low,8,NaN,Chat
2344,TKT002345,CUST02997,2025-12-24,Connectivity,Low,4,NaN,App
2943,TKT002944,CUST03777,2026-02-13,Plan Change,Low,5,NaN,Chat
3438,TKT003439,CUST04382,2026-03-07,Technical,Low,6,NaN,App
3457,TKT003458,CUST04406,2026-05-21,Plan Change,Low,1,NaN,Email
3884,TKT003885,CUST04935,2026-06-05,Cancellation,Low,2,NaN,Email
4193,TKT004194,CUST05301,2026-04-13,Connectivity,Low,3,NaN,App
4248,TKT004249,CUST05371,2025-11-15,Billing,Low,1,NaN,Chat
4905,TKT004906,CUST06246,2026-03-09,Cancellation,Medium,6,NaN,Phone
5686,TKT005687,CUST07226,2025-12-06,Cancellation,Low,4,NaN,Email
5967,TKT005968,CUST07622,2026-04-08,Other,Medium,5,NaN,App
6080,TKT006081,CUST07787,2026-05-04,Plan Change,Medium,3,NaN,App
6393,TKT006394,CUST08149,2025-12-25,Other,Low,6,NaN,Chat
6562,TKT006563,CUST08356,2026-04-26,Cancellation,Low,2,NaN,Email
6933,TKT006934,CUST08809,2025-12-07,Plan Change,Low,4,NaN,Email
7086,TKT007087,CUST09002,2025-04-16,Connectivity,High,4,NaN,Chat
7223,TKT007224,CUST09173,2024-11-28,Connectivity,Low,1,NaN,Phone
7225,TKT007226,CUST09177,2025-10-18,Other,Low,4,NaN,Phone
7262,TKT007263,CUST09225,2025-07-16,Connectivity,Low,10,NaN,Phone
7358,TKT007359,CUST09354,2026-02-28,Cancellation,Low,5,NaN,Chat
7726,TKT007727,CUST09847,2025-05-17,Technical,High,6,NaN,Chat
8645,TKT008646,CUST11124,2025-02-12,Connectivity,Medium,1,NaN,App
8677,TKT008678,CUST11162,2025-11-28,Billing,High,5,NaN,Email
9132,TKT009133,CUST11752,2025-07-18,Plan Change,Low,1,NaN,Email

In [176]:
support_tickets["Ticket_Date"] =pd.to_datetime(support_tickets["Ticket_Date"])

In [177]:
support_tickets.dtypes

Ticket_ID                        str
Customer_ID                      str
Ticket_Date           datetime64[us]
Issue_Type                       str
Priority                         str
Resolution_Days                int64
Satisfaction_Score           float64
Contact_Channel                  str
dtype: object

In [178]:
monthly_usage.shape

(150567, 7)

In [179]:
monthly_usage.columns

Index(['Usage_ID', 'Customer_ID', 'Usage_Month', 'Usage_Hours', 'Sessions',
       'Data_Usage_GB', 'Usage_Issue_Count'],
      dtype='str')

In [180]:
monthly_usage.head()

,Usage_ID,Customer_ID,Usage_Month,Usage_Hours,Sessions,Data_Usage_GB,Usage_Issue_Count
0,U00001_01,CUST00001,2025-10-01,18.47,16,29.66,0
1,U00001_02,CUST00001,2025-11-01,23.56,25,27.31,0
2,U00001_03,CUST00001,2025-12-01,27.21,19,12.87,1
3,U00001_04,CUST00001,2026-01-01,10.30,20,24.97,1
4,U00001_05,CUST00001,2026-02-01,3.89,14,33.11,1

In [181]:
monthly_usage.tail()

,Usage_ID,Customer_ID,Usage_Month,Usage_Hours,Sessions,Data_Usage_GB,Usage_Issue_Count
150562,U11999_17,CUST11999,2025-07-01,33.85,5,42.75,1
150563,U12000_01,CUST12000,2026-02-01,45.05,29,30.51,2
150564,U12000_02,CUST12000,2026-03-01,51.21,17,32.56,2
150565,U12000_03,CUST12000,2026-04-01,5.54,19,11.28,2
150566,U12000_04,CUST12000,2026-05-01,24.52,19,22.51,3

In [182]:
monthly_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 150567 entries, 0 to 150566
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Usage_ID           150567 non-null  str
 1   Customer_ID        150567 non-null  str
 2   Usage_Month        150567 non-null  str
 3   Usage_Hours        150567 non-null  float64
 4   Sessions           150567 non-null  int64
 5   Data_Usage_GB      150567 non-null  float64
 6   Usage_Issue_Count  150567 non-null  int64
dtypes: float64(2), int64(2), str(3)
memory usage: 12.1 MB

In [183]:
monthly_usage.dtypes

Usage_ID                 str
Customer_ID              str
Usage_Month              str
Usage_Hours          float64
Sessions               int64
Data_Usage_GB        float64
Usage_Issue_Count      int64
dtype: object

In [184]:
monthly_usage.describe()

         Usage_Hours       Sessions  Data_Usage_GB  Usage_Issue_Count
count  150567.000000  150567.000000  150567.000000      150567.000000
mean       22.395737      17.512503      28.439502           0.861676
std        12.537094       6.941551      11.629390           0.941200
min         1.000000       1.000000       0.200000           0.000000
25%        13.220000      13.000000      20.640000           0.000000
50%        20.110000      17.000000      28.840000           1.000000
75%        29.100000      22.000000      36.530000           1.000000
max       113.140000      47.000000      73.870000           8.000000

In [185]:
monthly_usage.describe(include="all")

,Usage_ID,Customer_ID,Usage_Month,Usage_Hours,Sessions,Data_Usage_GB,Usage_Issue_Count
count,150567,150567,150567,150567.000000,150567.000000,150567.000000,150567.000000
unique,150567,12000,29,NaN,NaN,NaN,NaN
top,U00001_01,CUST00008,2026-02-01,NaN,NaN,NaN,NaN
freq,1,18,7582,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,22.395737,17.512503,28.439502,0.861676
std,NaN,NaN,NaN,12.537094,6.941551,11.629390,0.941200
min,NaN,NaN,NaN,1.000000,1.000000,0.200000,0.000000
25%,NaN,NaN,NaN,13.220000,13.000000,20.640000,0.000000
50%,NaN,NaN,NaN,20.110000,17.000000,28.840000,1.000000
75%,NaN,NaN,NaN,29.100000,22.000000,36.530000,1.000000
max,NaN,NaN,NaN,113.140000,47.000000,73.870000,8.000000

In [189]:
monthly_usage["Customer_ID"].is_unique

False

In [190]:
monthly_usage["Usage_ID"].is_unique

True

In [191]:
monthly_usage["Usage_Month"].is_unique

False

In [193]:
monthly_usage["Usage_ID"].nunique()

150567

In [195]:
monthly_usage["Usage_ID"].nunique()==len(monthly_usage)

True

In [197]:
monthly_usage["Usage_ID"].value_counts(dropna=False)

Usage_ID
U00001_01    1
U00001_02    1
U00001_03    1
U00001_04    1
U00001_05    1
            ..
U11999_17    1
U12000_01    1
U12000_02    1
U12000_03    1
U12000_04    1
Name: count, Length: 150567, dtype: int64

In [198]:
monthly_usage["Usage_ID"].duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
150562    False
150563    False
150564    False
150565    False
150566    False
Name: Usage_ID, Length: 150567, dtype: bool

In [199]:
monthly_usage[monthly_usage["Usage_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Usage_ID, Customer_ID, Usage_Month, Usage_Hours, Sessions, Data_Usage_GB, Usage_Issue_Count]
Index: []

In [200]:
monthly_usage.isnull().sum()

Usage_ID             0
Customer_ID          0
Usage_Month          0
Usage_Hours          0
Sessions             0
Data_Usage_GB        0
Usage_Issue_Count    0
dtype: int64

In [201]:
monthly_usage.isnull().values.any()

np.False_

In [202]:
monthly_usage["Usage_ID"].isnull().sum()

np.int64(0)

In [203]:
monthly_usage.isna().sum()

Usage_ID             0
Customer_ID          0
Usage_Month          0
Usage_Hours          0
Sessions             0
Data_Usage_GB        0
Usage_Issue_Count    0
dtype: int64

In [204]:
monthly_usage[monthly_usage["Usage_ID"].isna()]

Empty DataFrame
Columns: [Usage_ID, Customer_ID, Usage_Month, Usage_Hours, Sessions, Data_Usage_GB, Usage_Issue_Count]
Index: []

In [205]:
monthly_usage["Usage_Month"] = pd.to_datetime(monthly_usage["Usage_Month"])

In [206]:
monthly_usage.dtypes

Usage_ID                        str
Customer_ID                     str
Usage_Month          datetime64[us]
Usage_Hours                 float64
Sessions                      int64
Data_Usage_GB               float64
Usage_Issue_Count             int64
dtype: object

In [209]:
print(customers.columns.tolist())
print(payments.columns.tolist())
print(subscriptions.columns.tolist())
print(support_tickets.columns.tolist())
print(monthly_usage.columns.tolist())

['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'State', 'Region', 'Signup_Date', 'Acquisition_Channel', 'Primary_Device', 'Customer_Status', 'Churn_Date']
['Payment_ID', 'Customer_ID', 'Payment_Date', 'Amount', 'Payment_Method', 'Payment_Status']
['Subscription_ID', 'Customer_ID', 'Plan', 'Monthly_Fee', 'Contract_Type', 'Support_Tier', 'Start_Date']
['Ticket_ID', 'Customer_ID', 'Ticket_Date', 'Issue_Type', 'Priority', 'Resolution_Days', 'Satisfaction_Score', 'Contact_Channel']
['Usage_ID', 'Customer_ID', 'Usage_Month', 'Usage_Hours', 'Sessions', 'Data_Usage_GB', 'Usage_Issue_Count']

In [210]:
#total customers, active and churned customers
# total
customers["Customer_ID"].nunique()

12000

In [211]:
#active and churned
customers["Customer_Status"].value_counts()

Customer_Status
Active     10394
Churned     1606
Name: count, dtype: int64

In [223]:
#total churned rate = total/churned * 100
churn_rate = (
    (customers["Customer_Status"] == "Churned").sum()
    / len(customers)
) * 100
print(churn_rate)
print(f"{churn_rate:.2f}%")
print(f"{churn_rate:.0f}%")

13.383333333333333
13.38%
13%

In [215]:
#churn rate by region
customers.groupby("Region")["Customer_Status"].value_counts()

Region  Customer_Status
East    Active             2577
        Churned             404
North   Active             2587
        Churned             377
South   Active             2595
        Churned             410
West    Active             2635
        Churned             415
Name: count, dtype: int64

In [232]:
churn_by_region = (
    customers.groupby("Region")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100)
)
print(churn_by_region)
print(churn_by_region.round(2).astype(str) + "%")
print(churn_by_region.round(2))

Region
East     13.552499
North    12.719298
South    13.643927
West     13.606557
Name: Customer_Status, dtype: float64
Region
East     13.55%
North    12.72%
South    13.64%
West     13.61%
Name: Customer_Status, dtype: str
Region
East     13.55
North    12.72
South    13.64
West     13.61
Name: Customer_Status, dtype: float64

In [235]:
customers.groupby("Acquisition_Channel")["Customer_Status"].value_counts()

Acquisition_Channel  Customer_Status
Mobile App           Active             2601
                     Churned             383
Partner              Active             2549
                     Churned             439
Retail Store         Active             2579
                     Churned             379
Website              Active             2665
                     Churned             405
Name: count, dtype: int64

In [240]:
churn_by_acq_ch = (customers.groupby("Acquisition_Channel")["Customer_Status"].apply(lambda x: (x=="Churned").mean()*100))
print (churn_by_acq_ch)
print (churn_by_acq_ch.round(2))
print (churn_by_acq_ch.round(2).astype(str) + "%")

Acquisition_Channel
Mobile App      12.835121
Partner         14.692102
Retail Store    12.812711
Website         13.192182
Name: Customer_Status, dtype: float64
Acquisition_Channel
Mobile App      12.84
Partner         14.69
Retail Store    12.81
Website         13.19
Name: Customer_Status, dtype: float64
Acquisition_Channel
Mobile App      12.84%
Partner         14.69%
Retail Store    12.81%
Website         13.19%
Name: Customer_Status, dtype: str

In [241]:
customers.groupby("Age")["Customer_Status"].value_counts()

Age  Customer_Status
18   Active             189
     Churned             36
19   Active             197
     Churned             34
20   Active             186
                       ...
66   Churned             30
67   Active             207
     Churned             32
68   Active             181
     Churned             32
Name: count, Length: 102, dtype: int64

In [242]:
churn_by_age = (customers.groupby("Age")["Customer_Status"].apply(lambda x: (x=="Churned").mean()*100))
print (churn_by_acq_ch)
print (churn_by_acq_ch.round(2))
print (churn_by_acq_ch.round(2).astype(str) + "%")

Acquisition_Channel
Mobile App      12.835121
Partner         14.692102
Retail Store    12.812711
Website         13.192182
Name: Customer_Status, dtype: float64
Acquisition_Channel
Mobile App      12.84
Partner         14.69
Retail Store    12.81
Website         13.19
Name: Customer_Status, dtype: float64
Acquisition_Channel
Mobile App      12.84%
Partner         14.69%
Retail Store    12.81%
Website         13.19%
Name: Customer_Status, dtype: str

In [243]:
customers.groupby("Primary_Device")["Customer_Status"].value_counts()

Primary_Device  Customer_Status
Android         Active             2577
                Churned             409
Smart TV        Active             2616
                Churned             407
Web             Active             2551
                Churned             425
iOS             Active             2650
                Churned             365
Name: count, dtype: int64

In [244]:
churn_by_age = (customers.groupby("Primary_Device")["Customer_Status"].apply(lambda x: (x=="Churned").mean()*100))
print (churn_by_acq_ch)
print (churn_by_acq_ch.round(2))
print (churn_by_acq_ch.round(2).astype(str) + "%")

Acquisition_Channel
Mobile App      12.835121
Partner         14.692102
Retail Store    12.812711
Website         13.192182
Name: Customer_Status, dtype: float64
Acquisition_Channel
Mobile App      12.84
Partner         14.69
Retail Store    12.81
Website         13.19
Name: Customer_Status, dtype: float64
Acquisition_Channel
Mobile App      12.84%
Partner         14.69%
Retail Store    12.81%
Website         13.19%
Name: Customer_Status, dtype: str

In [245]:
customers["Churn_Month"] = customers["Churn_Date"].dt.to_period("M")

In [250]:
monthly_churn = customers["Churn_Month"].value_counts().sort_index()
print(monthly_churn)

Churn_Month
2026-03    366
2026-04    383
2026-05    477
2026-06    380
Freq: M, Name: count, dtype: int64

In [252]:
customers["Churn_Month"] = customers["Churn_Date"].dt.to_period("M")

monthly_churn = (
    customers["Churn_Month"]
    .value_counts()
    .sort_index()
)
print(monthly_churn)

Churn_Month
2026-03    366
2026-04    383
2026-05    477
2026-06    380
Freq: M, Name: count, dtype: int64

In [253]:
customers.loc[
    customers["Customer_Status"] == "Churned",
    "Churn_Date"
].dt.to_period("M").nunique()

4

In [254]:
customers.loc[
    customers["Customer_Status"] == "Churned",
    "Churn_Date"
].dt.to_period("M").unique()

<PeriodArray>
['2026-05', '2026-04', '2026-03', '2026-06']
Length: 4, dtype: period[M]

In [255]:
churned = customers[customers["Customer_Status"] == "Churned"].copy()

In [256]:
print(churned)

      Customer_ID   Customer_Name  Age  Gender     City           State  \
6       CUST00007  Customer_00007   38  Female    Surat         Gujarat
26      CUST00027  Customer_00027   47  Female   Indore  Madhya Pradesh
37      CUST00038  Customer_00038   66  Female    Surat         Gujarat
43      CUST00044  Customer_00044   60   Other  Chennai      Tamil Nadu
46      CUST00047  Customer_00047   22  Female  Kolkata     West Bengal
...           ...             ...  ...     ...      ...             ...
11957   CUST11958  Customer_11958   63   Other   Indore  Madhya Pradesh
11966   CUST11967  Customer_11967   59  Female    Surat         Gujarat
11980   CUST11981  Customer_11981   67   Other  Chennai      Tamil Nadu
11983   CUST11984  Customer_11984   26  Female    Surat         Gujarat
11993   CUST11994  Customer_11994   41   Other   Mumbai     Maharashtra

      Region Signup_Date Acquisition_Channel Primary_Device Customer_Status  \
6       West  2026-04-04             Website            Web         Churned
26      West  2026-04-16          Mobile App       Smart TV         Churned
37      West  2024-12-11             Partner        Android         Churned
43     South  2024-11-09             Partner            Web         Churned
46      East  2024-04-26             Website            Web         Churned
...      ...         ...                 ...            ...             ...
11957   West  2025-01-27             Partner        Android         Churned
11966   West  2025-07-12             Partner       Smart TV         Churned
11980  South  2026-01-22             Website            iOS         Churned
11983   West  2024-01-04             Website            Web         Churned
11993   West  2025-08-12             Website        Android         Churned

      Churn_Date Churn_Month
6     2026-05-04     2026-05
26    2026-05-26     2026-05
37    2026-05-17     2026-05
43    2026-04-02     2026-04
46    2026-05-30     2026-05
...          ...         ...
11957 2026-04-09     2026-04
11966 2026-05-24     2026-05
11980 2026-03-05     2026-03
11983 2026-05-07     2026-05
11993 2026-04-19     2026-04

[1606 rows x 13 columns]

In [259]:
churned["Customer_Lifetime_Days"] = (
    churned["Churn_Date"] - churned["Signup_Date"]
).dt.days

In [265]:
churned[
    ["Customer_ID", "Signup_Date", "Churn_Date", "Customer_Lifetime_Days"]
].head(12000)

      Customer_ID Signup_Date Churn_Date  Customer_Lifetime_Days
6       CUST00007  2026-04-04 2026-05-04                      30
26      CUST00027  2026-04-16 2026-05-26                      40
37      CUST00038  2024-12-11 2026-05-17                     522
43      CUST00044  2024-11-09 2026-04-02                     509
46      CUST00047  2024-04-26 2026-05-30                     764
...           ...         ...        ...                     ...
11957   CUST11958  2025-01-27 2026-04-09                     437
11966   CUST11967  2025-07-12 2026-05-24                     316
11980   CUST11981  2026-01-22 2026-03-05                      42
11983   CUST11984  2024-01-04 2026-05-07                     854
11993   CUST11994  2025-08-12 2026-04-19                     250

[1606 rows x 4 columns]

In [268]:
churned["Customer_Lifetime_Days"].mean().round(2)

np.float64(404.88)

In [272]:
churned["Customer_Lifetime_Days"].agg(["mean", "median", "min", "max"]).round(2)

mean      404.88
median    393.00
min        30.00
max       897.00
Name: Customer_Lifetime_Days, dtype: float64

In [273]:
subscriptions.head()

,Subscription_ID,Customer_ID,Plan,Monthly_Fee,Contract_Type,Support_Tier,Start_Date
0,SUB00001,CUST00001,Standard,799,Monthly,5,2025-10-16
1,SUB00002,CUST00002,Family,1499,Monthly,15,2025-06-01
2,SUB00003,CUST00003,Premium,1199,Monthly,10,2026-02-16
3,SUB00004,CUST00004,Family,1499,Monthly,15,2025-09-10
4,SUB00005,CUST00005,Basic,499,Annual,2,2025-12-22

In [285]:
subscriptions.groupby("Plan")["Customer_ID"].nunique()

Plan
Basic       3093
Family      2969
Premium     2974
Standard    2964
Name: Customer_ID, dtype: int64

In [286]:
subscriptions.groupby("Plan")["Subscription_ID"].nunique()

Plan
Basic       3093
Family      2969
Premium     2974
Standard    2964
Name: Subscription_ID, dtype: int64

In [296]:
plan_churn = pd.merge(
    subscriptions[["Customer_ID", "Plan"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)
print(plan_churn)

      Customer_ID      Plan Customer_Status
0       CUST00001  Standard          Active
1       CUST00002    Family          Active
2       CUST00003   Premium          Active
3       CUST00004    Family          Active
4       CUST00005     Basic          Active
...           ...       ...             ...
11995   CUST11996  Standard          Active
11996   CUST11997     Basic          Active
11997   CUST11998    Family          Active
11998   CUST11999   Premium          Active
11999   CUST12000     Basic          Active

[12000 rows x 3 columns]

In [295]:
plan_churn_rate = (
    plan_churn.groupby("Plan")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100)
)
print (plan_churn_rate)

Plan
Basic       15.648238
Family      11.384304
Premium     13.147276
Standard    13.259109
Name: Customer_Status, dtype: float64

In [297]:
contract_churn = pd.merge(
    subscriptions[["Customer_ID", "Contract_Type"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)
print(contract_churn)

      Customer_ID Contract_Type Customer_Status
0       CUST00001       Monthly          Active
1       CUST00002       Monthly          Active
2       CUST00003       Monthly          Active
3       CUST00004       Monthly          Active
4       CUST00005        Annual          Active
...           ...           ...             ...
11995   CUST11996       Monthly          Active
11996   CUST11997       Monthly          Active
11997   CUST11998       Monthly          Active
11998   CUST11999        Annual          Active
11999   CUST12000       Monthly          Active

[12000 rows x 3 columns]

In [298]:
contract_churn_rate = (
    contract_churn.groupby("Contract_Type")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100)
)
print (contract_churn_rate)

Contract_Type
Annual        6.540840
Monthly      17.450800
Quarterly    11.143211
Name: Customer_Status, dtype: float64

In [299]:
support_churn = pd.merge(
    subscriptions[["Customer_ID", "Support_Tier"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)
print(support_churn)

      Customer_ID  Support_Tier Customer_Status
0       CUST00001             5          Active
1       CUST00002            15          Active
2       CUST00003            10          Active
3       CUST00004            15          Active
4       CUST00005             2          Active
...           ...           ...             ...
11995   CUST11996             5          Active
11996   CUST11997             2          Active
11997   CUST11998            15          Active
11998   CUST11999            10          Active
11999   CUST12000             2          Active

[12000 rows x 3 columns]

In [300]:
support_churn_rate = (
    support_churn.groupby("Support_Tier")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100)
)
print (support_churn_rate)

Support_Tier
2     15.648238
5     13.259109
10    13.147276
15    11.384304
Name: Customer_Status, dtype: float64

In [301]:
#average montly fee- active vs churned customers
fee = pd.merge(
    subscriptions[["Customer_ID", "Monthly_Fee"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)
print(fee)

      Customer_ID  Monthly_Fee Customer_Status
0       CUST00001          799          Active
1       CUST00002         1499          Active
2       CUST00003         1199          Active
3       CUST00004         1499          Active
4       CUST00005          499          Active
...           ...          ...             ...
11995   CUST11996          799          Active
11996   CUST11997          499          Active
11997   CUST11998         1499          Active
11998   CUST11999         1199          Active
11999   CUST12000          499          Active

[12000 rows x 3 columns]

In [310]:
avg_monthly_fee = (
    "churned_fee",fee.groupby("Monthly_Fee")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100),"active_fee",fee.groupby("Monthly_Fee")["Customer_Status"]
    .apply(lambda y: (y == "Active").mean() * 100)
)
print (avg_monthly_fee)

('churned_fee', Monthly_Fee
499     15.648238
799     13.259109
1199    13.147276
1499    11.384304
Name: Customer_Status, dtype: float64, 'active_fee', Monthly_Fee
499     84.351762
799     86.740891
1199    86.852724
1499    88.615696
Name: Customer_Status, dtype: float64)

In [311]:
churn_by_fee = (
    fee.groupby("Monthly_Fee")["Customer_Status"]
    .value_counts(normalize=True)
    .mul(100)
    .unstack(fill_value=0)
)

print(churn_by_fee)

Customer_Status     Active    Churned
Monthly_Fee
499              84.351762  15.648238
799              86.740891  13.259109
1199             86.852724  13.147276
1499             88.615696  11.384304

In [319]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 117501 entries, 0 to 117500
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Payment_ID      117501 non-null  str
 1   Customer_ID     117501 non-null  str
 2   Payment_Date    117501 non-null  datetime64[us]
 3   Amount          117501 non-null  int64
 4   Payment_Method  117501 non-null  str
 5   Payment_Status  117501 non-null  str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 9.3 MB

In [320]:
payments["Amount"].sum()

np.int64(240125205)

In [327]:
payments.groupby("Payment_Method")["Amount"].sum()

Payment_Method
AutoPay        45613126
Credit Card    48310982
Debit Card     47899705
Net Banking    49227651
UPI            49073741
Name: Amount, dtype: int64

In [359]:
#monthly revenue trend
#payments["Payment_Month"] = payments["Payment_Date"].dt.to_period("M")
monthly_trend = (payments["Payment_Month"].value_counts().sort_index())
print(monthly_trend)
#the above query shows number of transactions per month not the actual fee

Payment_Month
2024-01     431
2024-02     816
2024-03    1240
2024-04    1665
2024-05    2100
2024-06    2513
2024-07    2923
2024-08    3347
2024-09    3765
2024-10    4195
2024-11    4632
2024-12    5090
2025-01    5048
2025-02    5088
2025-03    5109
2025-04    5107
2025-05    5128
2025-06    5150
2025-07    5169
2025-08    5165
2025-09    5184
2025-10    5187
2025-11    5176
2025-12    5161
2026-01    5223
2026-02    5222
2026-03    5194
2026-04    5123
2026-05    2350
Freq: M, Name: count, dtype: int64

In [360]:
monthly_revenue = (payments.groupby("Payment_Month")["Amount"].sum())

print(monthly_revenue)

Payment_Month
2024-01      988814
2024-02     1638158
2024-03     2480267
2024-04     3245358
2024-05     4385413
2024-06     5480792
2024-07     6092857
2024-08     6917254
2024-09     7725866
2024-10     8888596
2024-11     9438142
2024-12    10400852
2025-01    10303909
2025-02    10120917
2025-03     9910190
2025-04    10014408
2025-05    10326484
2025-06    10196603
2025-07    10540317
2025-08    10603224
2025-09    10637437
2025-10    11102750
2025-11    10398168
2025-12    10754340
2026-01    10671309
2026-02    10979126
2026-03    10494871
2026-04    10434931
2026-05     4953852
Freq: M, Name: Amount, dtype: int64

In [331]:
payments["Payment_Status"].value_counts()

Payment_Status
Success    108402
Failed       9099
Name: count, dtype: int64

In [335]:
successful_payments = payments[
    payments["Payment_Status"] == "Completed"
]

In [340]:
monthly_revenue = (
    successful_payments.groupby("Payment_Month")["Amount"]
    .sum()
)

print(monthly_revenue)

Series([], Freq: M, Name: Amount, dtype: int64)

In [365]:
successful_payments = payments[
    payments["Payment_Status"] == "Success"
]

monthly_revenue = (
    successful_payments.groupby("Payment_Month")["Amount"]
    .sum()
)

print(monthly_revenue)

Payment_Month
2024-01      896800
2024-02     1421483
2024-03     2206129
2024-04     2926681
2024-05     4048133
2024-06     5013817
2024-07     5598868
2024-08     6323657
2024-09     7080731
2024-10     8108988
2024-11     8727473
2024-12     9679003
2025-01     9506030
2025-02     9313790
2025-03     9067555
2025-04     9288129
2025-05     9538607
2025-06     9451053
2025-07     9915968
2025-08     9732794
2025-09     9787899
2025-10    10273959
2025-11     9608670
2025-12     9845558
2026-01     9830677
2026-02     9996090
2026-03     9723533
2026-04     9734341
2026-05     4602109
Freq: M, Name: Amount, dtype: int64

In [364]:
payments[payments["Payment_Status"] == "Success"].groupby("Payment_Method")["Amount"].sum()

Payment_Method
AutoPay        44227837
Credit Card    44112763
Debit Card     43598524
Net Banking    44748194
UPI            44561207
Name: Amount, dtype: int64

In [367]:
payments[payments["Payment_Status"] == "Success"]["Amount"].sum()

np.int64(221248525)

In [368]:
#revenue by payment method
print(successful_payments.groupby("Payment_Method")["Amount"].sum())

Payment_Method
AutoPay        44227837
Credit Card    44112763
Debit Card     43598524
Net Banking    44748194
UPI            44561207
Name: Amount, dtype: int64

In [379]:
#payment failure rate by payment method
payments[payments["Payment_Status"] == "Failed"].groupby("Payment_Method")["Amount"].sum()

Payment_Method
AutoPay        1385289
Credit Card    4198219
Debit Card     4301181
Net Banking    4479457
UPI            4512534
Name: Amount, dtype: int64

In [376]:
payment_failure_rate = (
    payments.groupby("Payment_Method")["Payment_Status"]
    .apply(lambda x: (x == "Failed").mean() * 100)
)

print(payment_failure_rate)

Payment_Method
AutoPay        3.090671
Credit Card    9.086641
Debit Card     8.731622
Net Banking    8.691878
UPI            8.984623
Name: Payment_Status, dtype: float64

In [380]:
#average payment amount - active vs churned
#amount, customer status, mean, customer id
avg_pay_amount = pd.merge (payments[["Customer_ID", "Amount"]],customers[["Customer_ID", "Customer_Status"]],
                          on = "Customer_ID", how = "left")
print (avg_pay_amount)

       Customer_ID  Amount Customer_Status
0        CUST00001     799          Active
1        CUST00001     799          Active
2        CUST00001     799          Active
3        CUST00001     799          Active
4        CUST00001     799          Active
...            ...     ...             ...
117496   CUST11999   14388          Active
117497   CUST12000     499          Active
117498   CUST12000     499          Active
117499   CUST12000     499          Active
117500   CUST12000     499          Active

[117501 rows x 3 columns]

In [385]:
avg_pay = (
    avg_pay_amount.groupby("Customer_Status")["Amount"]
    .mean()
)

print(avg_pay)

Customer_Status
Active     2115.337608
Churned    1560.756431
Name: Amount, dtype: float64

In [386]:
avg_pay_amount = pd.merge(
    payments[["Customer_ID", "Amount", "Payment_Status"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)

In [387]:
avg_pay = (
    avg_pay_amount.groupby(
        ["Customer_Status", "Payment_Status"]
    )["Amount"]
    .mean()
)

print(avg_pay)

Customer_Status  Payment_Status
Active           Failed            2158.271169
                 Success           2111.756060
Churned          Failed            1535.170213
                 Success           1562.993418
Name: Amount, dtype: float64

In [388]:
support_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 9365 entries, 0 to 9364
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticket_ID           9365 non-null   str
 1   Customer_ID         9365 non-null   str
 2   Ticket_Date         9365 non-null   datetime64[us]
 3   Issue_Type          9365 non-null   str
 4   Priority            9365 non-null   str
 5   Resolution_Days     9365 non-null   int64
 6   Satisfaction_Score  9330 non-null   float64
 7   Contact_Channel     9365 non-null   str
dtypes: datetime64[us](1), float64(1), int64(1), str(5)
memory usage: 912.5 KB

In [395]:
support_tickets["Ticket_ID"].is_unique

True

In [397]:
support_tickets["Ticket_ID"].nunique()

9365

In [401]:
#tickets by issue types
support_tickets.groupby("Issue_Type")["Ticket_ID"].nunique()

Issue_Type
Billing         1572
Cancellation    1547
Connectivity    1586
Other           1526
Plan Change     1571
Technical       1563
Name: Ticket_ID, dtype: int64

In [405]:
#avg resolution days by issue type
support_tickets.groupby("Issue_Type")["Resolution_Days"].mean()

Issue_Type
Billing         3.713740
Cancellation    3.812540
Connectivity    3.756620
Other           3.796855
Plan Change     3.739020
Technical       3.645553
Name: Resolution_Days, dtype: float64

In [412]:
support_tickets["Resolution_Days"].mean()

np.float64(3.743726641751201)

In [415]:
#avg satisfactory score - active vs churned
avg_satisfactory_score = pd.merge (
    support_tickets[["Customer_ID","Satisfaction_Score"]],
    customers[["Customer_ID","Customer_Status"]],
    on = "Customer_ID", how = "left"
)

avg_score = (avg_satisfactory_score.groupby("Customer_Status")["Satisfaction_Score"].mean())
print (avg_score)

Customer_Status
Active     3.649097
Churned    3.672423
Name: Satisfaction_Score, dtype: float64

In [417]:
#churn rate by satisfaction score group
churn_satisfaction = pd.merge(
    support_tickets[["Customer_ID", "Satisfaction_Score"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)

churn_satisfaction["Satisfaction_Group"] = pd.cut(
    churn_satisfaction["Satisfaction_Score"],
    bins=[0, 2, 3, 5],
    labels=["Low", "Medium", "High"]
)
churn_rate = (
    churn_satisfaction.groupby("Satisfaction_Group")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100)
)

print(churn_rate)

Satisfaction_Group
Low       19.358974
Medium    21.368895
High      21.202648
Name: Customer_Status, dtype: float64

In [423]:
%whos

Variable                 Type         Data/Info
-----------------------------------------------
avg_monthly_fee          tuple        n=4
avg_pay                  Series       Shape: (4,)
avg_pay_amount           DataFrame    Shape: (117501, 4)
avg_satisfactory_score   DataFrame    Shape: (9365, 3)
avg_score                Series       Shape: (2,)
churn_by_acq_ch          Series       Shape: (4,)
churn_by_age             Series       Shape: (4,)
churn_by_fee             DataFrame    Shape: (4, 2)
churn_by_region          Series       Shape: (4,)
churn_rate               Series       Shape: (3,)
churn_satisfaction       DataFrame    Shape: (9365, 4)
churned                  DataFrame    Shape: (1606, 14)
contract_churn           DataFrame    Shape: (12000, 3)
contract_churn_rate      Series       Shape: (3,)
customers                DataFrame    Shape: (12000, 13)
failure_payments         DataFrame    Shape: (9099, 7)
fee                      DataFrame    Shape: (12000, 3)
monthly_churn            Series       Shape: (4,)
monthly_revenue          Series       Shape: (29,)
monthly_trend            Series       Shape: (29,)
monthly_usage            DataFrame    Shape: (150567, 7)
np                       module       <module 'numpy' from '/Li<...>kages/numpy/__init__.py'>
payment_failure_rate     Series       Shape: (5,)
payments                 DataFrame    Shape: (117501, 7)
pd                       module       <module 'pandas' from '/L<...>ages/pandas/__init__.py'>
plan_churn               DataFrame    Shape: (12000, 3)
plan_churn_rate          Series       Shape: (4,)
subscriptions            DataFrame    Shape: (12000, 7)
successful_payments      DataFrame    Shape: (108402, 7)
support_churn            DataFrame    Shape: (12000, 3)
support_churn_rate       Series       Shape: (4,)
support_tickets          DataFrame    Shape: (9365, 8)

In [424]:
#avg usage hours - active vs churned
monthly_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 150567 entries, 0 to 150566
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Usage_ID           150567 non-null  str
 1   Customer_ID        150567 non-null  str
 2   Usage_Month        150567 non-null  datetime64[us]
 3   Usage_Hours        150567 non-null  float64
 4   Sessions           150567 non-null  int64
 5   Data_Usage_GB      150567 non-null  float64
 6   Usage_Issue_Count  150567 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(2), str(2)
memory usage: 10.6 MB

In [425]:
avg_usage = pd.merge(monthly_usage[["Customer_ID", "Usage_Hours"]],
                     customers[["Customer_ID","Customer_Status"]],
                     on = "Customer_ID", how = "left")

avg_usage_hours = (avg_usage.groupby("Customer_Status")["Usage_Hours"].mean())
print (avg_usage_hours)

Customer_Status
Active     22.392160
Churned    22.419958
Name: Usage_Hours, dtype: float64

In [426]:
#avg sessions - active vs churned
sessions = pd.merge(monthly_usage[["Customer_ID", "Sessions"]],
                     customers[["Customer_ID","Customer_Status"]],
                     on = "Customer_ID", how = "left")

avg_sessions = (sessions.groupby("Customer_Status")["Sessions"].mean())
print (avg_sessions)

Customer_Status
Active     17.512962
Churned    17.509395
Name: Sessions, dtype: float64

In [428]:
#avg data usage - active vs churned
data_usage = pd.merge(monthly_usage[["Customer_ID", "Data_Usage_GB"]],
                     customers[["Customer_ID","Customer_Status"]],
                     on = "Customer_ID", how = "left")

avg_data_usage = (data_usage.groupby("Customer_Status")["Data_Usage_GB"].mean())
print (avg_data_usage)

Customer_Status
Active     28.531290
Churned    27.817878
Name: Data_Usage_GB, dtype: float64

In [430]:
#avg usage issue - active vs churned
usage_issue = pd.merge(monthly_usage[["Customer_ID", "Usage_Issue_Count"]],
                     customers[["Customer_ID","Customer_Status"]],
                     on = "Customer_ID", how = "left")

avg_usage_issue = (usage_issue.groupby("Customer_Status")["Usage_Issue_Count"].mean().round(2))
print (avg_usage_issue)

Customer_Status
Active     0.85
Churned    0.91
Name: Usage_Issue_Count, dtype: float64

In [432]:
#customer value vs churn
# Customer value vs churn

successful_payments = payments[
    payments["Payment_Status"] == "Success"
]

customer_value = (
    successful_payments.groupby("Customer_ID")["Amount"]
    .sum()
    .reset_index()
)

customer_value_churn = pd.merge(
    customer_value,
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)

value_vs_churn = (
    customer_value_churn.groupby("Customer_Status")["Amount"]
    .mean().round(2)
)

print(value_vs_churn)

Customer_Status
Active     19223.23
Churned    13619.68
Name: Amount, dtype: float64

In [433]:
# Subscription Plan vs Churn

plan_churn = pd.merge(
    subscriptions[["Customer_ID", "Plan"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)

churn_rate_by_plan = (
    plan_churn.groupby("Plan")["Customer_Status"]
    .apply(lambda x: (x == "Churned").mean() * 100)
)

print(churn_rate_by_plan)

Plan
Basic       15.648238
Family      11.384304
Premium     13.147276
Standard    13.259109
Name: Customer_Status, dtype: float64

In [437]:
[name for name, value in globals().items() if isinstance(value, pd.DataFrame)]

['customers',
 'payments',
 'subscriptions',
 'support_tickets',
 'monthly_usage',
 '_5',
 '_10',
 '_11',
 '_14',
 '_15',
 '_18',
 '_19',
 '_21',
 '_22',
 '_31',
 '_50',
 '_51',
 '_54',
 '_55',
 '_66',
 '_67',
 '_74',
 '_83',
 '_84',
 '_92',
 '_93',
 '_100',
 '_110',
 '_121',
 '_123',
 '_124',
 '_128',
 '_129',
 '_163',
 '_164',
 '_174',
 '_180',
 '_181',
 '_184',
 '_185',
 '_199',
 '_204',
 'churned',
 '_260',
 '_262',
 '_263',
 '_264',
 '_265',
 '_273',
 'plan_churn',
 'contract_churn',
 'support_churn',
 'fee',
 'churn_by_fee',
 'successful_payments',
 'failure_payments',
 'avg_pay_amount',
 '_406',
 '_407',
 'avg_satisfactory_score',
 'churn_satisfaction',
 'avg_usage',
 'sessions',
 'data_usage',
 'usage_issue',
 'customer_value',
 'customer_value_churn']

In [439]:
[name for name, value in globals().items() if isinstance(value, pd.DataFrame)][:5]

['customers', 'payments', 'subscriptions', 'support_tickets', 'monthly_usage']

In [440]:
# Does support experience differ between active and churned customers
# Support experience vs churn

support_churn = pd.merge(
    support_tickets[["Customer_ID", "Resolution_Days"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)

support_experience = (
    support_churn.groupby("Customer_Status")["Resolution_Days"]
    .mean()
)

print(support_experience)

Customer_Status
Active     3.732440
Churned    3.785931
Name: Resolution_Days, dtype: float64

In [441]:
usage_issue_churn = pd.merge(
    monthly_usage[["Customer_ID", "Usage_Issue_Count"]],
    customers[["Customer_ID", "Customer_Status"]],
    on="Customer_ID",
    how="left"
)

avg_usage_issues = (
    usage_issue_churn.groupby("Customer_Status")["Usage_Issue_Count"]
    .mean()
)

print(avg_usage_issues)

Customer_Status
Active     0.853836
Churned    0.914774
Name: Usage_Issue_Count, dtype: float64

In [442]:
avg_usage_issues = (
    usage_issue_churn.groupby("Customer_Status")["Usage_Issue_Count"]
    .mean()
)

difference = (
    avg_usage_issues["Churned"] - avg_usage_issues["Active"]
)

percentage_difference = (
    difference / avg_usage_issues["Active"]
) * 100

print("Average Usage Issues:")
print(avg_usage_issues.round(2))

print("\nDifference:", round(difference, 2))
print("Percentage Difference:", round(percentage_difference, 2), "%")

Average Usage Issues:
Customer_Status
Active     0.85
Churned    0.91
Name: Usage_Issue_Count, dtype: float64

Difference: 0.06
Percentage Difference: 7.14 %

In [443]:
# Filter only churned customers
churned_customers = customers[
    customers["Customer_Status"] == "Churned"
].copy()

# 1. Age profile
age_profile = churned_customers["Age"].agg(
    ["mean", "median", "min", "max"]
).round(2)

# 2. Gender profile
gender_profile = (
    churned_customers["Gender"]
    .value_counts()
)

# 3. Region profile
region_profile = (
    churned_customers["Region"]
    .value_counts()
)

# 4. Acquisition Channel profile
acquisition_profile = (
    churned_customers["Acquisition_Channel"]
    .value_counts()
)

# 5. Primary Device profile
device_profile = (
    churned_customers["Primary_Device"]
    .value_counts()
)

# 6. Top 10 cities by churn
city_profile = (
    churned_customers["City"]
    .value_counts()
    .head(10)
)

# 7. Top 10 states by churn
state_profile = (
    churned_customers["State"]
    .value_counts()
    .head(10)
)

# Display results
print("AGE PROFILE")
print(age_profile)

print("\nGENDER PROFILE")
print(gender_profile)

print("\nREGION PROFILE")
print(region_profile)

print("\nACQUISITION CHANNEL PROFILE")
print(acquisition_profile)

print("\nPRIMARY DEVICE PROFILE")
print(device_profile)

print("\nTOP 10 CITIES BY CHURN")
print(city_profile)

print("\nTOP 10 STATES BY CHURN")
print(state_profile)

AGE PROFILE
mean      42.51
median    42.00
min       18.00
max       68.00
Name: Age, dtype: float64

GENDER PROFILE
Gender
Other     581
Male      555
Female    470
Name: count, dtype: int64

REGION PROFILE
Region
West     415
South    410
East     404
North    377
Name: count, dtype: int64

ACQUISITION CHANNEL PROFILE
Acquisition_Channel
Partner         439
Website         405
Mobile App      383
Retail Store    379
Name: count, dtype: int64

PRIMARY DEVICE PROFILE
Primary_Device
Web         425
Android     409
Smart TV    407
iOS         365
Name: count, dtype: int64

TOP 10 CITIES BY CHURN
City
Kochi         97
Indore        95
Mumbai        90
Guwahati      89
Kolkata       86
Chandigarh    86
Patna         85
Ahmedabad     84
Bengaluru     84
Surat         81
Name: count, dtype: int64

TOP 10 STATES BY CHURN
State
Gujarat           165
Tamil Nadu        155
Maharashtra       155
Uttar Pradesh     149
Kerala             97
Madhya Pradesh     95
Assam              89
West Bengal        86
Chandigarh         86
Bihar              85
Name: count, dtype: int64

In [444]:
#null satisfaction score
# Number of missing satisfaction scores
missing_count = support_tickets["Satisfaction_Score"].isna().sum()

# Total support tickets
total_tickets = len(support_tickets)

# Percentage of tickets with missing satisfaction scores
missing_percentage = (
    missing_count / total_tickets
) * 100

print("Missing Satisfaction Scores:", missing_count)
print("Total Support Tickets:", total_tickets)
print("Missing Percentage:", round(missing_percentage, 2), "%")

Missing Satisfaction Scores: 35
Total Support Tickets: 9365
Missing Percentage: 0.37 %

In [445]:
missing_satisfaction = support_tickets[
    support_tickets["Satisfaction_Score"].isna()
]

print("Missing Satisfaction Scores by Issue Type:")
print(
    missing_satisfaction["Issue_Type"]
    .value_counts()
)

print("\nMissing Satisfaction Scores by Priority:")
print(
    missing_satisfaction["Priority"]
    .value_counts()
)

print("\nMissing Satisfaction Scores by Contact Channel:")
print(
    missing_satisfaction["Contact_Channel"]
    .value_counts()
)

Missing Satisfaction Scores by Issue Type:
Issue_Type
Cancellation    8
Connectivity    7
Plan Change     7
Billing         5
Technical       4
Other           4
Name: count, dtype: int64

Missing Satisfaction Scores by Priority:
Priority
Low       21
Medium    10
High       4
Name: count, dtype: int64

Missing Satisfaction Scores by Contact Channel:
Contact_Channel
App      11
Email    10
Phone     7
Chat      7
Name: count, dtype: int64

In [446]:
print(
    missing_satisfaction["Resolution_Days"]
    .describe()
)

count    35.000000
mean      4.342857
std       2.743365
min       1.000000
25%       2.500000
50%       4.000000
75%       6.000000
max      12.000000
Name: Resolution_Days, dtype: float64

In [449]:
print("Resolution days — Missing Satisfaction Score:")
print(
    missing_satisfaction["Resolution_Days"].mean().round(2)
)

print("\nResolution days — Satisfaction Score Available:")
print(
    support_tickets[
        support_tickets["Satisfaction_Score"].notna()
    ]["Resolution_Days"].mean().round(2)
)

Resolution days — Missing Satisfaction Score:
4.34

Resolution days — Satisfaction Score Available:
3.74

In [450]:
# Export cleaned DataFrames as new CSV files
# Original/raw CSV files are NOT overwritten.

customers.to_csv("customers_clean.csv", index=False)
payments.to_csv("payments_clean.csv", index=False)
subscriptions.to_csv("subscriptions_clean.csv", index=False)
support_tickets.to_csv("support_tickets_clean.csv", index=False)
monthly_usage.to_csv("monthly_usage_clean.csv", index=False)

print("Cleaned files exported successfully:")
print("1. customers_clean.csv")
print("2. payments_clean.csv")
print("3. subscriptions_clean.csv")
print("4. support_tickets_clean.csv")
print("5. monthly_usage_clean.csv")

Cleaned files exported successfully:
1. customers_clean.csv
2. payments_clean.csv
3. subscriptions_clean.csv
4. support_tickets_clean.csv
5. monthly_usage_clean.csv

In [451]:
import os

for file in [
    "customers_clean.csv",
    "payments_clean.csv",
    "subscriptions_clean.csv",
    "support_tickets_clean.csv",
    "monthly_usage_clean.csv"
]:
    print(file, os.path.getsize(file), "bytes")

customers_clean.csv 1153455 bytes
payments_clean.csv 7281014 bytes
subscriptions_clean.csv 631551 bytes
support_tickets_clean.csv 541283 bytes
monthly_usage_clean.csv 7145829 bytes

In [452]:
print(support_tickets.shape)

(9365, 8)